spring.application.name=ms-security
server.port=8080

# MongoDB
spring.mongodb.uri=mongodb+srv://sebastianherrera45451:R7oB5GvUCSTaG0oH@backend.bkvqlbn.mongodb.net/
spring.mongodb.database=db_security

# JWT
jwt.secret=clave_secreta_muy_larga_y_segura_para_produccion
jwt.expiration=3600000

# Microservicio de notificaciones (ms-notificaciones Flask en puerto 5000)
notification.service.url=http://localhost:5000
