spring.application.name=ms-security
server.port=8080

# MongoDB
spring.mongodb.uri=mongodb+srv://sebastianherrera45451:R7oB5GvUCSTaG0oH@backend.bkvqlbn.mongodb.net/
spring.mongodb.database=db_security

# JWT
jwt.secret=aaa
jwt.expiration=3600000

# Microservicio de notificaciones
notification.service.url= http://localhost:5000
